import java.time.LocalDate

object CafeLogic {

  val coke: Drink = Drink("Coke", 1.00, 10)
  val lemonade: Drink = Drink("Lemonade", 1.00, 10)
  val cake: ColdFood = ColdFood("Cake", 2.00, 5)
  val sandwich: ColdFood = ColdFood("Sandwich", 2.00, 5)
  val pie: HotFood = HotFood("Pie", 3.00, 5)
  val pasty: HotFood = HotFood("Pasty", 3.00, 5)
  val steak: PremiumFood = PremiumFood("Steak", 5.00, 5)
  val fish: PremiumFood = PremiumFood("Fish", 5.00, 5)
  val roast: PremiumFood = PremiumFood("Roast", 5.00, 0)
  val lanNone: Customer = Customer("Lan", None, LocalDate.of(1978,2,10))
  val lan: Customer = Customer("Lan", Some(DrinksCard(List(1,1,1,1))), LocalDate.of(1978,2,10))
  val lanExtendCard: Customer = Customer("lan", Some(DiscountCard(Nil)), LocalDate.of(1978,2,11))
  val orderHotFood = Order(List((coke, 1), (pie,2)), lan)
  val foodOnlyOrder = Order(List((pie,2)), lan)
  val billFoodOnly = Bill(List(foodOnlyOrder), RegularServiceCharge, None)
  val billHotFood = Bill(List(orderHotFood), RegularServiceCharge,None)
  val largeOrderWithPremium = Order(List((lemonade,2), (coke, 1), (roast, 1),(fish,2)), lan)
  val tooBigOrder = Order(List((lemonade,20), (coke, 1), (roast, 1),(fish,2)), lan)
  val largeBillWithPremium = Bill(List(orderHotFood, largeOrderWithPremium), AdditionalService, Some(8.00))
  println(orderHotFood)
  println(billHotFood)
  println(billHotFood)
  println(billHotFood)
  println(billHotFood.getServiceCharge)
  println(largeOrderWithPremium)
  println(largeBillWithPremium)
  println(largeBillWithPremium.getServiceCharge)

  val firstMenu = Menu(List(coke,lemonade), List(cake, sandwich), List(pie, pasty), List(steak))
  println(firstMenu)
  println(firstMenu.addPremiumFood(PremiumFood("Seafood Platter", 50.00, 2)))
  println(firstMenu.removePremiumFood(steak))
  println(billHotFood.getNetTotal)
  println(billHotFood.getNetTotal)
  println("getNetTotal: " + largeBillWithPremium.getNetTotal)
  //println(largeBillWithPremium.applyServiceCharge)
  println(largeOrderWithPremium.orderItems)
  println(firstMenu.addPremiumFood((PremiumFood("Seafood Platter", 50.00, 2))))
  println(tooBigOrder.processOrder(tooBigOrder.orderItems))
  println(billHotFood.getLoyaltyCard)
  println(billHotFood.isDrinkInOrder(billHotFood.orders))
  println(billFoodOnly.isDrinkInOrder(billFoodOnly.orders))
  println("not working?: " + billHotFood.stampCard)
}
