object CafeLogic extends App {

  val coke = Drink("Coke", 2.00, 10)
  val lemonade = Drink("Lemonade", 1.00, 10)
  val cake = ColdFood("Cake", 4.00, 5)
  val sandwich = ColdFood("Sandwich", 3.00, 5)
  val pie = HotFood("Pie", 5.00, 5)
  val pasty = HotFood("Pasty", 4.00, 5)
  val steak = PremiumFood("Steak", 25.00, 5)
  val fish = PremiumFood("Fish", 20.00, 5)
  val roast = PremiumFood("Roast", 22.00, 0)

  val orderHotFood = Order(List((coke, 1), (pie,2)), 1)
  val billHotFood = Bill(List(orderHotFood), RegularServiceCharge,None)
  val largeOrderWithPremium = Order(List((lemonade,2), (coke, 1), (roast, 1),(fish,2)), 1)
  val largeBillWithPremium = Bill(List(orderHotFood, largeOrderWithPremium), AdditionalService, Some(8.00))
  println(orderHotFood)
  println(billHotFood)
  println(billHotFood)
  println(billHotFood)
  println(billHotFood.getServiceCharge)
  println(largeOrderWithPremium)
  println(largeBillWithPremium)
  println(largeBillWithPremium.getServiceCharge)

  val firstMenu = Menu(List(coke,lemonade), List(cake, sandwich), List(pie, pasty), List(steak))
  println(firstMenu)
  println(firstMenu.addPremiumFood(PremiumFood("Seafood Platter", 50.00, 2)))
  println(firstMenu.removePremiumFood(steak))
  println(billHotFood.getNetTotal)
  println(billHotFood.getNetTotal)
  println(largeBillWithPremium.getNetTotal)
  println(largeBillWithPremium.applyServiceCharge)
  println(largeOrderWithPremium.orderItems)
}
